services:
  cassandradb:
    build: .
    container_name: cassandradb
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - $PWD/data_warehouse/data:/var/lib/cassandra

networks:
  default:
    external:
      name: cassandra-network
